plugins:
  - '@salesforce-ux/stylelint-plugin-slds'

overrides:
  - files:
      - '**/*.css'
      - '**/*.scss'
    customSyntax: 'postcss'
    rules:
      length-zero-no-unit:
        - true
        - severity: warning
      slds/no-slds-class-overrides:
        - true
        - severity: warning
      # slds/no-important-tag:
      #   - true
      #   - severity: warning
      # slds/no-hardcoded-values-slds1:
      #   - true
      #   - severity: error
      slds/no-hardcoded-values-slds2:
        - true
        - severity: warning
      # slds/no-deprecated-tokens-slds1:
      #   - true
      #   - severity: error
      # slds/lwc-token-to-slds-hook: ## Cannot be public as the data is not final. 
      #   - true
      #   - severity: warning
      # slds/enforce-bem-usage:
      #   - true
      #   - severity: warning
      # slds/no-deprecated-slds-classes:
      #   - true
      #   - severity: warning
      slds/no-slds-private-var:
        - true
        - severity: warning
      # slds/no-calc-function:
      #   - true
      #   - severity: warning
      slds/enforce-sds-to-slds-hooks:
        - true
        - severity: warning
      slds/reduce-annotations:
        - true
        - severity: warning
      slds/no-unsupported-hooks-slds2:
        - true
        - severity: warning

    sourceMap:
      - false

  - files:
      - '**/*.html'
    customSyntax: 'postcss-html'
    rules: {}
